changelog:
  exclude:
    labels:
    - type/digest
  categories:
  - title: Major Updates
    labels:
    - type/major
  - title: Minor Updates
    labels:
    - type/minor
  - title: Other Changes
    labels:
    - "*"
