name: Build and Package vscode extension

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
  workflow_dispatch:
  workflow_call:

jobs:
  binaries:
    name: Download yamlfmt binaries
    uses: ./.github/workflows/yamlfmt-binaries.yaml

  package:
    name: package vscode extension
    needs: binaries
    if: success()
    uses: ./.github/workflows/package.yaml
