name: Build and Package vscode extension

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    name: Build yamlfmt
    uses: ./.github/workflows/build.yaml

  package:
    name: package vscode extension
    needs: build
    if: success()
    uses: ./.github/workflows/package.yaml