name: Build yamlfmt from source

on:
  workflow_call:

env:
  go: 1.18
  repo_path: kubernetes-yaml-formatter-x

jobs:
  build:
    name: Build yamlfmt binary
    runs-on: ubuntu-latest
    steps:

    - name: Checkout main repo
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      with:
        fetch-depth: 0
        path: ${{ env.repo_path }}

    - name: Read External Repo
      id: read-repo
      run: |
        YAMLFMT_REPO=$(jq -r '.["github-releases"]["yamlfmt"]["repo"]' ${repo_path}/dependencies.json)
        echo "YAMLFMT_REPO=$YAMLFMT_REPO" >> "${GITHUB_OUTPUT}"

    - name: Read External Repo Version
      id: read-version
      run: |
        YAMLFMT_VERSION=$(jq -r '.["github-releases"]["yamlfmt"]["version"]' ${repo_path}/dependencies.json)
        echo "YAMLFMT_VERSION=$YAMLFMT_VERSION" >> "${GITHUB_OUTPUT}"

    - name: Cleanup repo
      run: rm -rf ${{ env.repo_path }}

    - name: Checkout yamlfmt repo
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      with:
        fetch-depth: 0
        repository: ${{ steps.read-repo.outputs.YAMLFMT_REPO }}
        ref: ${{ steps.read-version.outputs.YAMLFMT_VERSION }}

    - name: Setup golang
      uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5
      with:
        go-version: ${{ env.go }}
        check-latest: true

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@286f3b13b1b49da4ac219696163fb8c1c93e1200 # v6
      with:
        distribution: goreleaser
        version: latest
        args: --snapshot --rm-dist

    - name: Cleanup
      run: rm -rf *.tar.gz

    - name: Upload yamlfmt binaries
      uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4
      with:
        name: binaries
        path: "dist/yamlfmt_*"
