name: Build yamlfmt from source

on:
  workflow_call:

env:
  go: 1.18
  repo_path: kubernetes-yaml-formatter-x

jobs:
  build:
    name: Build yamlfmt binary
    runs-on: ubuntu-latest
    steps:

    - name: Checkout main repo
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      with:
        fetch-depth: 0
        path: ${{ env.repo_path }}

    - name: Read External Repo
      id: read-repo
      run: |
        YAMLFMT_REPO=$(jq -r '.["github-releases"]["yamlfmt"]["repo"]' ${repo_path}/dependencies.json)
        echo "$YAMLFMT_REPO" >> "${GITHUB_OUTPUT}"

    - name: Read External Repo Version
      id: read-version
      run: |
        YAMLFMT_VERSION=$(jq -r '.["github-releases"]["yamlfmt"]["version"]' ${repo_path}/dependencies.json)
        echo "$YAMLFMT_VERSION" >> "${GITHUB_OUTPUT}"

    - name: Cleanup repo
      run: rm -rf ${{ env.repo_path }}

    - name: Checkout yamlfmt repo
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      with:
        fetch-depth: 0
        repository: ${{ steps.read-repo.outputs.YAMLFMT_REPO }}
        ref: ${{ steps.read-version.outputs.YAMLFMT_VERSION }}

    - name: Setup golang
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5
      with:
        go-version: ${{ env.go }}
        check-latest: true

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@7ec5c2b0c6cdda6e8bbb49444bc797dd33d74dd8 # v5
      with:
        distribution: goreleaser
        version: latest
        args: --snapshot --rm-dist

    - name: Cleanup
      run: rm -rf *.tar.gz

    - name: Upload yamlfmt binaries
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4
      with:
        name: binaries
        path: "dist/yamlfmt_*"
