# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Check Package
on:
  pull_request:
    branches:
    - main

jobs:
  check-package:
    name: Package
    uses: ./.github/workflows/package.yaml
