name: Package vscode extension

on:
  workflow_call:
    inputs:
      version:
        description: 'yamlfmt version'
        required: true
        type: string

env:
  # TODO: Renovate node version to match the package version
  node_version: 20

jobs:
  validations:
    name: Validations
    runs-on: ubuntu-latest
    steps:
    - name: Validate version string
      run: |
        if [[ ! ${{ inputs.version }} =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Invalid version string. Please provide a valid version string in the format v1.2.3"
          exit 1
        fi
    - name: Strip v from version
      run: echo "VERSION=${version/v/}" >> $GITHUB_ENV
      env:
        version: ${{ inputs.version }}

  package:
    name: Package vscode extension
    runs-on: ubuntu-latest
    needs: validations
    strategy:
      matrix:
        os:
        - os: win32-x64
          bin: Windows_x86_64
        - os: win32-arm64
          bin: Windows_arm64
        - os: linux-x64
          bin: Linux_x86_64
        - os: linux-arm64
          bin: Linux_arm64
        - os: darwin-x64
          bin: Darwin_x86_64
        - os: darwin-arm64
          bin: Darwin_arm64
    steps:
    - uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4
      with:
        name: yamlfmt_${{ env.VERSION }}_${{ matrix.os.bin }}
        path: /tmp

    - name: Checkout extension repo
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      with:
        fetch-depth: 0

    - name: Setup nodejs
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
      with:
        node-version: ${{ env.node_version }}

    - name: Npm install
      run: npm install

    - name: Package multi-platforms
      shell: bash
      run: |
        mv "/tmp/yamlfmt*" bin/
        chmod +x -R bin/
        npx vsce package --target ${{ matrix.os.os }}

    - name: Upload artifacts (vsix files)
      uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4
      with:
        name: packages
        path: "*.vsix"
