name: release to visual studio code extension marketplace

on:
  push:
    tags:
    - "*"
  workflow_dispatch:
  pull_request:
    branches:
    - main

jobs:
  build:
    name: build yamlfmt binary
    runs-on: ubuntu-latest
    steps:
    - name: Checkout yamlfmt repo
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      with:
        fetch-depth: 0
        repository: google/yamlfmt
        ref: v0.11.0
    - name: setup golang
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5
      with:
        go-version: '1.18'
        check-latest: true
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@7ec5c2b0c6cdda6e8bbb49444bc797dd33d74dd8 # v5
      with:
        distribution: goreleaser
        version: latest
        args: --snapshot --rm-dist
    - name: rm tar.gz
      run: rm -rf *.tar.gz
    - name: upload
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
      with:
        name: binaries
        path: "dist/yamlfmt_*"

  package:
    name: package vscode extension
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3
      with:
        name: binaries
        path: /tmp
    - name: checkout extension repo
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      with:
        fetch-depth: 0
    - name: setup nodejs
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
      with:
        node-version: 18
    - name: npm install
      run: npm install
    - name: package multi-platforms
      shell: bash
      run: |
        declare -A map
        map["win32-x64"]=windows_amd64_v1
        map["win32-arm64"]=windows_arm64
        map["linux-x64"]=linux_amd64_v1
        map["linux-arm64"]=linux_arm64
        map["darwin-x64"]=darwin_amd64_v1
        map["darwin-arm64"]=darwin_arm64

        for arch in ${!map[*]}; do
          rm -rf bin/
          mv "/tmp/yamlfmt_${map[$arch]}" bin/
          chmod +x -R bin/
          npx vsce package --target $arch
        done
    - name: upload
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
      with:
        name: packages
        path: "*.vsix"

  release:
    name: publish vscode extension to marketplace
    runs-on: ubuntu-latest
    needs: package
    if: success() && startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3
      with:
        name: packages
    - run: npx vsce publish --packagePath $(find . -iname '*.vsix')
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
