name: Full Release of Extension

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-and-package:
    name: Build and Package
    uses: ./.github/workflows/build-and-package.yaml

  release:
    name: publish vscode extension to marketplace
    runs-on: ubuntu-latest
    needs: build-and-package
    if: success() && startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Grab artifacts (vsix files)
      uses: actions/download-artifact@87c55149d96e628cc2ef7e6fc2aab372015aec85 # v4
      with:
        name: packages

    - id: set-matrix
      run: |
        FILES=$(find . -iname '*.vsix')
        JSON_STRING='['
        for FILE in $FILES; do
          JSON_STRING+='{"file":"'$FILE'"},'
        done
        JSON_STRING=$(echo $JSON_STRING | sed 's/,$//')']'
        echo "MATRIX_JSON=$JSON_STRING" >> $GITHUB_ENV
        echo "::set-output name=matrix::$JSON_STRING"

    - name: Publish to GitHub Releases
      uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
      if: success() && startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ steps.set-matrix.outputs.matrix }}
        generate_release_notes: true
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to VS Code Marketplace
      run: npx vsce publish --packagePath $(find . -iname '*.vsix')
      if: success() && startsWith(github.ref, 'refs/tags/')
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
