name: Full Release of Extension

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-and-package:
    name: Build and Package
    uses: ./.github/workflows/build-and-package.yaml

  release:
    name: publish vscode extension to marketplace
    runs-on: ubuntu-latest
    needs: build-and-package
    if: success() && startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Grab artifacts (vsix files)
      uses: actions/download-artifact@87c55149d96e628cc2ef7e6fc2aab372015aec85 # v4
      with:
        name: packages

    - name: Publish to VS Code Marketplace
      run: npx vsce publish --packagePath $(find . -iname '*.vsix')
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
