name: Gather yamlfmt binaries

on:
  workflow_call:
  workflow_dispatch:

env:
  # renovate: datasource=github-releases depName=google/yamlfmt
  version: v0.13.0

jobs:
  build:
    name: Get yamlfmt binaries
    runs-on: ubuntu-latest
    steps:
    - name: Download yamlfmt binaries from release
      uses: robinraju/release-downloader@v1.10
      with:
        repository: google/yamlfmt
        tag: ${{ env.version }}
        fileName: '*.tar.gz'
        extract: true
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: list files
      run: |
        ls -l

    # - name: upload yamlfmt as artifacts
    #   uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4
    #   with:
    #     path: yamlfmt_${{ env.version }}
