name: Gather yamlfmt binaries

on:
  workflow_call:
    inputs:
      version:
        description: 'yamlfmt version'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      version:
        description: 'yamlfmt version'
        required: true
        type: string

jobs:
  validations:
    name: Validations
    runs-on: ubuntu-latest
    outputs:
      VERSION_NUM: ${{ steps.strip.outputs.VERSION_NUM }}
    steps:
    - name: Validate version string
      run: |
        if [[ ! ${{ inputs.version }} =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Invalid version string. Please provide a valid version string in the format v1.2.3"
          exit 1
        fi
    - name: Strip v from version
      id: strip
      run: echo "VERSION_NUM=${version/v/}" >> $GITHUB_OUTPUT

  build:
    name: Get yamlfmt binaries
    runs-on: ubuntu-latest
    needs: validations
    strategy:
      fail-fast: false
      matrix:
        os:
        - Darwin_arm64
        - Darwin_x86_64
        - Linux_arm64
        - Linux_i386
        - Linux_x86_64
        - Windows_arm64
        - Windows_i386
        - Windows_x86_64
    steps:
    - name: Download yamlfmt binaries from release
      uses: robinraju/release-downloader@v1.10
      with:
        repository: google/yamlfmt
        tag: ${{ inputs.version }}
        fileName: 'yamlfmt_${{ needs.validations.outputs.VERSION_NUM }}_${{ matrix.os }}.tar.gz'
        extract: true
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: upload yamlfmt as artifacts
      uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4
      with:
        name: yamlfmt_${{ needs.validations.outputs.VERSION_NUM }}_${{ matrix.os }}
        if-no-files-found: error
        path: yamlfmt*
