name: Gather yamlfmt binaries

on:
  workflow_call:
  workflow_dispatch:

env:
  # renovate: datasource=github-releases depName=google/yamlfmt
  version: v0.13.0

jobs:
  build:
    name: Get yamlfmt binaries
    runs-on: ubuntu-latest
    steps:
    - name: Get yamlfmt binaries from release, all platforms
      uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4
      with:
        pattern: yamlfmt_*
        repository: google/yamlfmt

    - name: extract tar.gz
      run: |
        for f in yamlfmt_*.tar.gz; do
          tar -xzf $f
        done
        ls -l

    # - name: upload yamlfmt as artifacts
    #   uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4
    #   with:
    #     path: yamlfmt_${{ env.version }}
